### ISSUE TITLE
[1.16.x] GStringImpl cannot be cast to java.lang.String when using mixinbuild.gradle

### ISSUE THREAD

**Issue by nikita488** [SizableShrimp/ForgeTemplate#1]
I have downloaded 1.16.x branch of this template, renamed mixinbuild.gradle to build.gradle and imported to Intellij IDEA.
It stops with this error:
```
Build file 'D:\Dev\Minecraft\1.16.5\ForgeTemplate-1.16.x\build.gradle' line: 194

A problem occurred evaluating root project 'ExampleMod'.
> org.codehaus.groovy.runtime.GStringImpl cannot be cast to java.lang.String
```
The problematic line:
https://github.com/SizableShrimp/ForgeTemplate/blob/bf6d0c6501ec43bd49d6ec989afd5336ff755a5a/mixinbuild.gradle#L194

I tried to change `"${mod_id}.mixins.json"` inside `resourceTargets` array to `"${mod_id}.mixins.json".toString()` and it's importing fine. But it throws another error when I try to run `gradlew build`:
```
Execution failed for task ':processResources'.
> Could not copy file 'D:\Dev\Minecraft\1.16.5\ForgeTemplate-1.16.x\src\main\resources\examplemod.mixins.json' to 'D:\Dev\Minecraft\1.16.5\ForgeTemplate-1.16.x\build\resources\main\examplemod.mixins.json'.
   > Missing property (project) for Groovy template expansion. Defined keys [mod_id, mod_name, mod_version, mod_authors, mod_description, minecraft_version_range, forge_version_range, loader_version_range, out].
```

**Comment by SizableShrimp** [comment]
Fixed in 676765a5c3dd50ec1033ef1da3c75c80bb033701 and tested this time. Sorry about that, didn't test the mixinbuild.gradle thoroughly enough I guess.
